language: java
jdk:
  - openjdk11
  - openjdk13
script:
  - export extracted_java_version=`javac -version | sed 's/javac //g' | awk -F'.' '{print $1}'`
  - echo "Building project with java version ${extracted_java_version}"
  - mvn -B -Djava.version=${extracted_java_version} clean verify